float:
  euclidean:
    - base_args: ['@metric','@dimension']
      constructor: Kgn
      disabled: false
      docker_tag: ann-benchmarks-kgn
      module: ann_benchmarks.algorithms.kgn
      name: kgn
      run_groups:
        Kgn:
            args: 
              R: 160
              level: 2
            query_args: [[10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100, 105, 110, 120, 140, 150, 160, 180, 200, 300, 500]]
  angular:
    - base_args: ['@metric','@dimension']
      constructor: Kgn
      disabled: false
      docker_tag: ann-benchmarks-kgn
      module: ann_benchmarks.algorithms.kgn
      name: kgn
      run_groups:
        Kgn:
            args: 
              R: [128,160]
              level: [1,2]
            query_args: [[10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100, 105, 110, 115, 200, 300, 400, 500]]